# Generated by Django 4.2.26 on 2025-12-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer1_url', models.URLField()),
                ('freelancer2_url', models.URLField()),
                ('winner_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Comparison histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
