# Generated by Django 4.2.26 on 2025-12-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_url', models.URLField(unique=True)),
                ('specialty', models.CharField(max_length=100)),
                ('platform', models.CharField(default='upwork', max_length=50)),
                ('marketplace_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('marketplace_score', models.IntegerField(default=0)),
                ('fairfound_score', models.IntegerField(default=0)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('on_time_percentage', models.IntegerField(default=0)),
                ('response_time_hours', models.IntegerField(default=0)),
                ('rehire_rate', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fairfound_score'],
            },
        ),
    ]
